-- 코드를 입력하세요
SELECT ao.ANIMAL_ID, ao.ANIMAL_TYPE, ao.NAME
FROM ANIMAL_OUTS ao 
JOIN ANIMAL_INS ai ON ao.ANIMAL_ID = ai.ANIMAL_ID
WHERE ai.SEX_UPON_INTAKE like 'Intact%' AND ao.SEX_UPON_OUTCOME not like 'Intact%'
ORDER BY ao.ANIMAL_ID