-- 코드를 입력하세요
SELECT j.FLAVOR 
FROM FIRST_HALF fh 
JOIN (SELECT 
      SHIPMENT_ID, FLAVOR, sum(TOTAL_ORDER) AS 'TOTAL_ORDER'
      FROM JULY
     GROUP BY FLAVOR) j
ON j.FLAVOR = fh.FLAVOR
ORDER BY (j.TOTAL_ORDER + fh.TOTAL_ORDER) DESC
LIMIT 3